### ISSUE TITLE
一处可能导致hardfault的bug

### ISSUE THREAD

**Issue by jzz007** [RT-Thread-packages/mpu-6xxx#13]
在初始化部分
https://github.com/RT-Thread-packages/mpu-6xxx/blob/5c8bd63435e61de464c3b46b8a16c721be5258cf/src/sensor_inven_mpu6xxx.c#L247-L252
此处初始化失败之后free掉了申请的内存
https://github.com/RT-Thread-packages/mpu-6xxx/blob/5c8bd63435e61de464c3b46b8a16c721be5258cf/src/sensor_inven_mpu6xxx.c#L266-L272
但是前面向系统注册的设备还是在系统设备链表里面，之后再进行申请内存写值的时候就会破坏系统设备链表，进而访问不可访问的内存引发hardfault错误。建议这里初始化在设备注册成功的情况下不要free掉设备对象占用的内存

**Comment by Guozhanxin** [comment]
是的，有这种可能

**Comment by Guozhanxin** [comment]
多谢反馈，已修复：https://github.com/RT-Thread-packages/mpu-6xxx/pull/17
