### ISSUE TITLE
rt-thread 使用该软件包编译报错

### ISSUE THREAD

**Issue by chenyingchun0312** [RT-Thread-packages/mpu-6xxx#20]
![image](https://user-images.githubusercontent.com/44871523/143673863-6d1b9812-3548-489d-86bb-5bdabf43cf2c.png)

我这边的解决策略是，在mpu6xx.h中添加了一行 `#include <stdint.h>`， 但是我看该软件包中，大部分已经使用rt_uint32_t等类型，所以不是很清楚，到底应该统一使用c99标准头文件，还是rtt定义的类型

![image](https://user-images.githubusercontent.com/44871523/143673992-3bd560fe-a716-407d-a472-53b5f1a3a975.png)

**Comment by Guozhanxin** [comment]
可以的，这么解决就可以，可以提个pr上来吗？

**Comment by chenyingchun0312** [comment]
好的，可以的

**Comment by chenyingchun0312** [comment]
https://github.com/RT-Thread-packages/mpu-6xxx/issues/20
