### ISSUE TITLE
软件包中未看到使能PKG_USING_MPU6XXX_SAMPLE的配置

### ISSUE THREAD

**Issue by chenyingchun0312** [RT-Thread-packages/mpu-6xxx#21]
软件包中未看到使能PKG_USING_MPU6XXX_SAMPLE的配置，好像不能menuconfig 添加`samples/mpu6xxx_sample.c` 到工程中编译，需要手动添加该sample到工程中

![image](https://user-images.githubusercontent.com/44871523/143674065-d43cacc2-3f26-455d-9708-06871051735a.png)

**Comment by chenyingchun0312** [comment]
查看软件包的Kconfig文件，发现，只有当软件包版本是 PKG_USING_MPU6XXX_V001 才会自动使能 PKG_USING_MPU6XXX_SAMPLE 这个Sample，不是特别清楚什么原因，隐约感觉是对接了Sensor驱动框架后，不需要这个Sample了？但是使用Sensor驱动框架来读写这个传感器，还不太会！

![image](https://user-images.githubusercontent.com/44871523/143674191-bc2cdcbc-d286-4de3-b96e-541e937c208c.png)

**Comment by Guozhanxin** [comment]
是的，对接到传感器框架之后，就不需要使用之前的接口读写数据了。

**Comment by chenyingchun0312** [comment]
好的，谢谢，那我就去去学习一下sensor框架，看看如何操作
