### ISSUE TITLE
这个模块还在继续完善吗？

### ISSUE THREAD

**Issue by loveforeverLi** [RT-Thread-packages/mpu-6xxx#5]
使用过程存在些不解或者存在问题的地方，跟大家请教下：
Q1：
struct rt_sensor_config cfg;
    
    cfg.intf.dev_name = "i2c2";
    cfg.intf.user_data = (void *)MPU6XXX_ADDR_DEFAULT;
    cfg.irq_pin.pin = RT_PIN_NONE;

    rt_hw_mpu6xxx_init("mpu", &cfg);
请教下，rt_hw_mpu6xxx_init("mpu", &cfg); 这里的"mpu"不是注册的设备名称吗？为什么通过“i2c2"可以找到设备，"mpu"找不到呢？

Q2：中断管脚现在是不是还不支持呢？ 下一版本能否考虑加上这个？

Q3：通过rt_device_read读不到数据，有没有示例代码？

谢谢！！

**Comment by loveforeverLi** [comment]
Q3我理解可能有误，仿照mpu6xxx命令的代码进行读写，就好了。

**Comment by loveforeverLi** [comment]
Q1： acce_mpu或gyro_mpu可以检测到设备，名字是组合起来的，有点奇怪
Q2：sensor_cmd有中断方式的读取

**Comment by Guozhanxin** [comment]
因为对接了传感器框架，所以使用方式可以参考传感器的使用文档：https://docs.rt-thread.org/#/rt-thread-version/rt-thread-standard/programming-manual/device/sensor/sensor
